! allow(E001)
! =================================================================
!  GENERATED FILE — DO NOT EDIT.
!  Source:    src/model/registry.yaml
!  Generator: scripts/gen_registry.py   (rerun after registry edits)
!  Sync test: scripts/gen_registry.py --check
! =================================================================
!> @file config_defaults.f90
!> @brief Generated YAML-parameter default constants (registry single source).
module model_config_defaults_mod
   implicit none
   public

   ! ── breaking ──
   character(*), parameter :: DEF_BREAKING_CBRK1 = '0.65'
   character(*), parameter :: DEF_BREAKING_CBRK2 = '0.35'
   character(*), parameter :: DEF_BREAKING_NU_BKG = '0.0'
   character(*), parameter :: DEF_BREAKING_ROLLER = 'NO'
   character(*), parameter :: DEF_BREAKING_ROLLER_EFFECT = 'NO'
   character(*), parameter :: DEF_BREAKING_SHOW_BREAKING = 'YES'
   character(*), parameter :: DEF_BREAKING_VISBRK = '0.0'
   character(*), parameter :: DEF_BREAKING_WAVEMAKER_CBRK = '1.0'
   character(*), parameter :: DEF_BREAKING_WAVEMAKER_VIS = 'NO'
   character(*), parameter :: DEF_BREAKING_WAVEMAKER_VISBRK = '0.0'
   ! ── friction ──
   character(*), parameter :: DEF_FRICTION_CD = '0.0'
   character(*), parameter :: DEF_FRICTION_FRICTION_MATRIX = 'NO'
   character(*), parameter :: DEF_FRICTION_MANNING = 'NO'
   ! ── geometry ──
   character(*), parameter :: DEF_GEOMETRY_BATHY_CORRECTION = 'NO'
   character(*), parameter :: DEF_GEOMETRY_BATHY_TYPE = 'flat'
   ! ── hot_start ──
   character(*), parameter :: DEF_HOT_START_BED_DEFORMATION = 'NO'
   character(*), parameter :: DEF_HOT_START_OUTPUT_START_NUMBER = '0'
   character(*), parameter :: DEF_HOT_START_TIME = '0.0'
   ! ── numerics ──
   character(*), parameter :: DEF_NUMERICS_ARRTIMEMINH = '0.001'
   character(*), parameter :: DEF_NUMERICS_FROUDECAP = '3.0'
   character(*), parameter :: DEF_NUMERICS_MINDEPTH = '0.1'
   character(*), parameter :: DEF_NUMERICS_MINDEPTHFRC = '0.1'
   character(*), parameter :: DEF_NUMERICS_ARR_TIME_MIN_H = '0.001'
   character(*), parameter :: DEF_NUMERICS_CFL = '0.5'
   character(*), parameter :: DEF_NUMERICS_CONSTRUCTION = 'HLLC'
   character(*), parameter :: DEF_NUMERICS_FROUDE_CAP = '10.0'
   character(*), parameter :: DEF_NUMERICS_HIGH_ORDER = 'FOURTH'
   character(*), parameter :: DEF_NUMERICS_MIN_DEPTH = '0.001'
   character(*), parameter :: DEF_NUMERICS_MIN_DEPTH_FRC = '0.5'
   character(*), parameter :: DEF_NUMERICS_OUT_TIME = 'NO'
   character(*), parameter :: DEF_NUMERICS_TIME_SCHEME = 'Runge_Kutta'
   ! ── obstacle ──
   character(*), parameter :: DEF_OBSTACLE_BREAKWATERABSORBCOEF = '10.0'
   character(*), parameter :: DEF_OBSTACLE_BREAKWATER_ABSORB_COEF = '0.0'
   ! ── output ──
   character(*), parameter :: DEF_OUTPUT_ETABLOWVAL = '10.0'
   character(*), parameter :: DEF_OUTPUT_DEPTH_OUT = 'NO'
   character(*), parameter :: DEF_OUTPUT_ETA_BLOW_VAL = '1.0e8'
   character(*), parameter :: DEF_OUTPUT_FIELD_IO_TYPE = 'ASCII'
   character(*), parameter :: DEF_OUTPUT_NUMBER_STATIONS = '0'
   character(*), parameter :: DEF_OUTPUT_OUTPUT_RES = '1'
   character(*), parameter :: DEF_OUTPUT_RESULT_FOLDER = './output/'
   character(*), parameter :: DEF_OUTPUT_STEADY_TIME = '999999.0'
   character(*), parameter :: DEF_OUTPUT_T_INTV_MEAN = '999999.0'
   ! ── physics ──
   character(*), parameter :: DEF_PHYSICS_BETA_REF = '-0.531'
   character(*), parameter :: DEF_PHYSICS_BREAKING = 'NO'
   character(*), parameter :: DEF_PHYSICS_C_SMG = '0.0'
   character(*), parameter :: DEF_PHYSICS_DISP_TIME_LEFT = 'NO'
   character(*), parameter :: DEF_PHYSICS_DISPERSION = 'YES'
   character(*), parameter :: DEF_PHYSICS_GAMMA1 = '1.0'
   character(*), parameter :: DEF_PHYSICS_GAMMA2 = '1.0'
   character(*), parameter :: DEF_PHYSICS_GAMMA3 = '1.0'
   character(*), parameter :: DEF_PHYSICS_PERIODIC = 'NO'
   character(*), parameter :: DEF_PHYSICS_SEDIMENT = 'NO'
   character(*), parameter :: DEF_PHYSICS_SWE_ETA_DEP = '0.7'
   character(*), parameter :: DEF_PHYSICS_VISCOSITY_BREAKING = 'YES'
   character(*), parameter :: DEF_PHYSICS_WATER_LEVEL = '0.0'
   character(*), parameter :: DEF_PHYSICS_WAVEMAKER = 'NO'
   ! ── simulation ──
   character(*), parameter :: DEF_SIMULATION_PLOT_INTV_STATION = '1.0'
   character(*), parameter :: DEF_SIMULATION_SCREEN_INTERVAL = '1.0'
   character(*), parameter :: DEF_SIMULATION_STATION_OUTPUT_BUFFER = '1000'
   character(*), parameter :: DEF_SIMULATION_T_START = '0.0'
   character(*), parameter :: DEF_SIMULATION_TIME_STEPPING_FIXED_DT = 'NO'
   ! ── sponge ──
   character(*), parameter :: DEF_SPONGE_CDSPONGE = '5.0'
   character(*), parameter :: DEF_SPONGE_A_SPONGE = '5.0'
   character(*), parameter :: DEF_SPONGE_CD_SPONGE = '0.0'
   character(*), parameter :: DEF_SPONGE_CSP = '0.1'
   character(*), parameter :: DEF_SPONGE_DIFFUSION_SPONGE = 'NO'
   character(*), parameter :: DEF_SPONGE_DIRECT_SPONGE = 'NO'
   character(*), parameter :: DEF_SPONGE_FRICTION_SPONGE = 'NO'
   character(*), parameter :: DEF_SPONGE_R_SPONGE = '0.85'
   character(*), parameter :: DEF_SPONGE_SPONGE_EAST_WIDTH = '0.0'
   character(*), parameter :: DEF_SPONGE_SPONGE_NORTH_WIDTH = '0.0'
   character(*), parameter :: DEF_SPONGE_SPONGE_SOUTH_WIDTH = '0.0'
   character(*), parameter :: DEF_SPONGE_SPONGE_WEST_WIDTH = '0.0'
   ! ── wavemaker ──
   character(*), parameter :: DEF_WAVEMAKER_AMP = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_AMP_WK = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_A_SPONGE_WAVEMAKER = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_DEP = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_DEP_WK = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_DELTA_WK = '0.5'
   character(*), parameter :: DEF_WAVEMAKER_DEPTHWAVEMAKER = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_ETA_LIMITER = 'NO'
   character(*), parameter :: DEF_WAVEMAKER_EQUALENERGY = 'NO'
   character(*), parameter :: DEF_WAVEMAKER_FREQMAX = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_FREQMIN = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_FREQPEAK = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_GAMMATMA = '3.3'
   character(*), parameter :: DEF_WAVEMAKER_HMO = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_LAGTIME = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_NFREQ = '45'
   character(*), parameter :: DEF_WAVEMAKER_NTHETA = '1'
   character(*), parameter :: DEF_WAVEMAKER_NUMWAVECOMP = '1'
   character(*), parameter :: DEF_WAVEMAKER_PEAKPERIOD = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_R_SPONGE_WAVEMAKER = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_SIGMA_THETA = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_SOLITARYPOSITIVEDIRECTION = 'YES'
   character(*), parameter :: DEF_WAVEMAKER_THETAPEAK = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_THETA_WK = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_TIME_RAMP = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_TPERIOD = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_WAVE_DATA_TYPE = 'DATA_1D'
   character(*), parameter :: DEF_WAVEMAKER_WID = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_WAVEMAKERCD = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_WIDTHWAVEMAKER = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_XWAVEMAKER = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_XC = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_XC_WK = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_YC = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_YC_WK = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_YWIDTH_WK = '999999.0'
   character(*), parameter :: DEF_WAVEMAKER_A0_NWAVE = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_ALPHA_C = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_DEP_NWAVE = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_GAMMA_NWAVE = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_TYPE = 'nothing'
   character(*), parameter :: DEF_WAVEMAKER_X1_NWAVE = '0.0'
   character(*), parameter :: DEF_WAVEMAKER_X2_NWAVE = '0.0'

end module model_config_defaults_mod
