! allow(E001)
! =================================================================
!  GENERATED FILE — DO NOT EDIT.
!  Source:    src/model/registry.yaml
!  Generator: scripts/gen_registry.py   (rerun after registry edits)
!  Sync test: scripts/gen_registry.py --check
! =================================================================
!> @file config_defaults.f90
!> @brief Generated YAML-parameter default constants (registry single source).
module model_config_defaults_mod
   implicit none
   public

   ! ── boundaries ──
   character(*), parameter :: DEF_BOUNDARIES_EAST_SPONGE_DIFFUSION_NU = "0.1"
   character(*), parameter :: DEF_BOUNDARIES_EAST_SPONGE_DIRECT_A = "5.0"
   character(*), parameter :: DEF_BOUNDARIES_EAST_SPONGE_DIRECT_R = "0.85"
   character(*), parameter :: DEF_BOUNDARIES_EAST_SPONGE_FRICTION_CD = "0.0"
   character(*), parameter :: DEF_BOUNDARIES_EAST_SPONGE_WIDTH = "0.0"
   character(*), parameter :: DEF_BOUNDARIES_NORTH_SPONGE_DIFFUSION_NU = "0.1"
   character(*), parameter :: DEF_BOUNDARIES_NORTH_SPONGE_DIRECT_A = "5.0"
   character(*), parameter :: DEF_BOUNDARIES_NORTH_SPONGE_DIRECT_R = "0.85"
   character(*), parameter :: DEF_BOUNDARIES_NORTH_SPONGE_FRICTION_CD = "0.0"
   character(*), parameter :: DEF_BOUNDARIES_NORTH_SPONGE_WIDTH = "0.0"
   character(*), parameter :: DEF_BOUNDARIES_RELAXATION_CELLS = "30"
   character(*), parameter :: DEF_BOUNDARIES_SOUTH_SPONGE_DIFFUSION_NU = "0.1"
   character(*), parameter :: DEF_BOUNDARIES_SOUTH_SPONGE_DIRECT_A = "5.0"
   character(*), parameter :: DEF_BOUNDARIES_SOUTH_SPONGE_DIRECT_R = "0.85"
   character(*), parameter :: DEF_BOUNDARIES_SOUTH_SPONGE_FRICTION_CD = "0.0"
   character(*), parameter :: DEF_BOUNDARIES_SOUTH_SPONGE_WIDTH = "0.0"
   character(*), parameter :: DEF_BOUNDARIES_WEST_SPONGE_DIFFUSION_NU = "0.1"
   character(*), parameter :: DEF_BOUNDARIES_WEST_SPONGE_DIRECT_A = "5.0"
   character(*), parameter :: DEF_BOUNDARIES_WEST_SPONGE_DIRECT_R = "0.85"
   character(*), parameter :: DEF_BOUNDARIES_WEST_SPONGE_FRICTION_CD = "0.0"
   character(*), parameter :: DEF_BOUNDARIES_WEST_SPONGE_WIDTH = "0.0"
   ! ── breaking ──
   character(*), parameter :: DEF_BREAKING_CBRK1 = "0.65"
   character(*), parameter :: DEF_BREAKING_CBRK2 = "0.35"
   character(*), parameter :: DEF_BREAKING_MODEL = "eddy_viscosity"
   character(*), parameter :: DEF_BREAKING_NU_BKG = "0.0"
   character(*), parameter :: DEF_BREAKING_ROLLER = "NO"
   character(*), parameter :: DEF_BREAKING_ROLLER_EFFECT = "NO"
   character(*), parameter :: DEF_BREAKING_SHOW_BREAKING = "YES"
   character(*), parameter :: DEF_BREAKING_VISBRK = "0.0"
   character(*), parameter :: DEF_BREAKING_WAVEMAKER_CBRK = "1.0"
   character(*), parameter :: DEF_BREAKING_WAVEMAKER_VIS = "NO"
   character(*), parameter :: DEF_BREAKING_WAVEMAKER_VISBRK = "0.0"
   ! ── foam ──
   character(*), parameter :: DEF_FOAM_BURST_TIME_NON_BREAKING = "1.0"
   character(*), parameter :: DEF_FOAM_CD = "0.5"
   character(*), parameter :: DEF_FOAM_MIN_THICKNESS = "0.01"
   character(*), parameter :: DEF_FOAM_SOURCE_COEF = "0.05"
   character(*), parameter :: DEF_FOAM_TIME_SCALE = "3.8"
   ! ── friction ──
   character(*), parameter :: DEF_FRICTION_CD = "0.0"
   character(*), parameter :: DEF_FRICTION_FRICTION_MATRIX = "NO"
   character(*), parameter :: DEF_FRICTION_MANNING = "NO"
   ! ── grid ──
   character(*), parameter :: DEF_GRID_BATHY_CORRECTION = "NO"
   character(*), parameter :: DEF_GRID_BATHY_TYPE = "flat"
   ! ── hot_start ──
   character(*), parameter :: DEF_HOT_START_BED_DEFORMATION = "NO"
   character(*), parameter :: DEF_HOT_START_OUTPUT_START_NUMBER = "0"
   character(*), parameter :: DEF_HOT_START_TIME = "0.0"
   ! ── initial ──
   character(*), parameter :: DEF_INITIAL_SINE_MODE_AMPLITUDE = "0.0"
   character(*), parameter :: DEF_INITIAL_SINE_MODE_DEPTH = "0.0"
   character(*), parameter :: DEF_INITIAL_SINE_MODE_MODE_X = "1"
   character(*), parameter :: DEF_INITIAL_SINE_MODE_MODE_Y = "0"
   character(*), parameter :: DEF_INITIAL_SOLITARY_AMPLITUDE = "0.0"
   character(*), parameter :: DEF_INITIAL_SOLITARY_DEPTH = "0.0"
   character(*), parameter :: DEF_INITIAL_SOLITARY_DIRECTION = "+x"
   character(*), parameter :: DEF_INITIAL_SOLITARY_X_CENTER = "0.0"
   character(*), parameter :: DEF_INITIAL_WATER_LEVEL = "0.0"
   ! ── meteo ──
   character(*), parameter :: DEF_METEO_OUT_METEO = "YES"
   character(*), parameter :: DEF_METEO_HOLLAND_AIR_PRESSURE = "NO"
   character(*), parameter :: DEF_METEO_HOLLAND_CD = "0.002"
   character(*), parameter :: DEF_METEO_HOLLAND_WAVE_INTERACTION = "NO"
   character(*), parameter :: DEF_METEO_HOLLAND_WIND_FORCE = "NO"
   character(*), parameter :: DEF_METEO_WIND_CD = "0.002"
   character(*), parameter :: DEF_METEO_WIND_WAVE_INTERACTION = "NO"
   ! ── numerics ──
   character(*), parameter :: DEF_NUMERICS_CFL = "0.5"
   character(*), parameter :: DEF_NUMERICS_FLUX_SOLVER = "hllc"
   character(*), parameter :: DEF_NUMERICS_FROUDE_CAP = "3.0"
   character(*), parameter :: DEF_NUMERICS_MIN_DEPTH = "0.1"
   character(*), parameter :: DEF_NUMERICS_RECONSTRUCTION = "fourth"
   ! ── obstacle ──
   character(*), parameter :: DEF_OBSTACLE_BREAKWATER_ABSORB_COEF = "10.0"
   ! ── output ──
   character(*), parameter :: DEF_OUTPUT_ARRIVAL_TIME_MIN_HEIGHT = "0.001"
   character(*), parameter :: DEF_OUTPUT_DEPTH_OUT = "NO"
   character(*), parameter :: DEF_OUTPUT_ETA_BLOW_VAL = "1.0e8"
   character(*), parameter :: DEF_OUTPUT_FIELD_IO_TYPE = "ASCII"
   character(*), parameter :: DEF_OUTPUT_NUMBER_STATIONS = "0"
   character(*), parameter :: DEF_OUTPUT_OUTPUT_RES = "1"
   character(*), parameter :: DEF_OUTPUT_RESULT_FOLDER = "./output/"
   character(*), parameter :: DEF_OUTPUT_STEADY_TIME = "999999.0"
   character(*), parameter :: DEF_OUTPUT_T_INTV_MEAN = "999999.0"
   ! ── physics ──
   character(*), parameter :: DEF_PHYSICS_DISPERSION_BETA_REF = "-0.531"
   character(*), parameter :: DEF_PHYSICS_DISPERSION_SCHEME = "fully_nonlinear"
   character(*), parameter :: DEF_PHYSICS_DISPERSION_SWE_ETA_DEP = "0.8"
   ! ── precipitation ──
   character(*), parameter :: DEF_PRECIPITATION_OUT_PRECIPITATION = "YES"
   ! ── sediment ──
   character(*), parameter :: DEF_SEDIMENT_AVALANCHE = "NO"
   character(*), parameter :: DEF_SEDIMENT_BEDLOAD = "NO"
   character(*), parameter :: DEF_SEDIMENT_BED_CHANGE = "NO"
   character(*), parameter :: DEF_SEDIMENT_COHESIVESEDIMENT = "NO"
   character(*), parameter :: DEF_SEDIMENT_E_COH = "0.0001"
   character(*), parameter :: DEF_SEDIMENT_HARD_BOTTOM = "NO"
   character(*), parameter :: DEF_SEDIMENT_MINDEPTHPICKUP = "0.1"
   character(*), parameter :: DEF_SEDIMENT_MORPH_FACTOR = "1"
   character(*), parameter :: DEF_SEDIMENT_PICKUPREDUCTION = "YES"
   character(*), parameter :: DEF_SEDIMENT_REDUCTIONPARAMETER = "0.65"
   character(*), parameter :: DEF_SEDIMENT_SDENSITY = "2.68"
   character(*), parameter :: DEF_SEDIMENT_SED_SCHEME = "Upwinding"
   character(*), parameter :: DEF_SEDIMENT_SEDIMENTMASSSOURCE = "NO"
   character(*), parameter :: DEF_SEDIMENT_SEDIMENTMOMENTDC = "NO"
   character(*), parameter :: DEF_SEDIMENT_SEDIMENTMOMENTEXG = "NO"
   character(*), parameter :: DEF_SEDIMENT_SHIELDS_CR = "0.055"
   character(*), parameter :: DEF_SEDIMENT_SOFTBED = "YES"
   character(*), parameter :: DEF_SEDIMENT_TAN_PHI = "0.7"
   character(*), parameter :: DEF_SEDIMENT_TAU_CR_COH = "0.001"
   character(*), parameter :: DEF_SEDIMENT_TAU_CRD_COH = "0.001"
   character(*), parameter :: DEF_SEDIMENT_A_COH = "0.1"
   character(*), parameter :: DEF_SEDIMENT_ALPHA_COH = "1.0"
   character(*), parameter :: DEF_SEDIMENT_B_COH = "2.0"
   character(*), parameter :: DEF_SEDIMENT_K_COH = "1e-06"
   character(*), parameter :: DEF_SEDIMENT_M_COH = "1.5"
   character(*), parameter :: DEF_SEDIMENT_N_COH = "0.5"
   character(*), parameter :: DEF_SEDIMENT_N_POROSITY = "0.47"
   ! ── simulation ──
   character(*), parameter :: DEF_SIMULATION_PLOT_INTV_STATION = "1.0"
   character(*), parameter :: DEF_SIMULATION_SCREEN_INTERVAL = "1.0"
   character(*), parameter :: DEF_SIMULATION_STATION_OUTPUT_BUFFER = "1000"
   character(*), parameter :: DEF_SIMULATION_T_START = "0.0"
   character(*), parameter :: DEF_SIMULATION_TIME_STEPPING_FIXED_DT = "NO"
   ! ── subgrid ──
   character(*), parameter :: DEF_SUBGRID_RATIO = "1"
   character(*), parameter :: DEF_SUBGRID_WRITE_POROSITY = "NO"
   ! ── vessel ──
   character(*), parameter :: DEF_VESSEL_CLEARANCE = "1.0"
   character(*), parameter :: DEF_VESSEL_CDDEEPDRAFT = "0.1"
   character(*), parameter :: DEF_VESSEL_DEEP_DRAFT = "NO"
   character(*), parameter :: DEF_VESSEL_FRICTIONMETHOD = "YES"
   character(*), parameter :: DEF_VESSEL_MASKMETHOD = "YES"
   character(*), parameter :: DEF_VESSEL_NUMVESSEL = "1"
   character(*), parameter :: DEF_VESSEL_OUT_VESSEL = "YES"
   character(*), parameter :: DEF_VESSEL_PROPELLER = "NO"
   character(*), parameter :: DEF_VESSEL_VISDEEPDRAFT = "0.1"
   character(*), parameter :: DEF_VESSEL_VISCOSITYMETHOD = "NO"
   ! ── wavemaker ──
   character(*), parameter :: DEF_WAVEMAKER_SOURCE_DELTA = "0.5"
   character(*), parameter :: DEF_WAVEMAKER_SOURCE_DEPTH = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SOURCE_TIME_RAMP = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SOURCE_X_CENTER = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SOURCE_Y_CENTER = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SOURCE_Y_WIDTH = "999999.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_AMPLITUDE = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_DIRECTION = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_DIRECTIONAL_N_BINS = "1"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_DIRECTIONAL_PEAK = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_DIRECTIONAL_SPREAD = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_DISCRETIZATION_COHERENCE_PERCENT = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_DISCRETIZATION_EQUAL_ENERGY = "NO"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_DISCRETIZATION_FREQ_BINS = "45"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_DISCRETIZATION_METHOD = "grid"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_FORMAT = "DATA_1D"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_FREQ_MAX = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_FREQ_MIN = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_FREQ_PEAK = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_GAMMA = "3.3"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_HM0 = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_N = "1"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_PERIOD = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_PERIOD_PEAK = "0.0"

end module model_config_defaults_mod
