! allow(E001)
! =================================================================
!  GENERATED FILE — DO NOT EDIT.
!  Source:    src/model/registry.yaml
!  Generator: scripts/gen_registry.py   (rerun after registry edits)
!  Sync test: scripts/gen_registry.py --check
! =================================================================
!> @file config_defaults.f90
!> @brief Generated YAML-parameter default constants (registry single source).
module model_config_defaults_mod
   implicit none
   public

   ! ── breaking ──
   character(*), parameter :: DEF_BREAKING_CBRK1 = "0.65"
   character(*), parameter :: DEF_BREAKING_CBRK2 = "0.35"
   character(*), parameter :: DEF_BREAKING_NU_BKG = "0.0"
   character(*), parameter :: DEF_BREAKING_ROLLER = "NO"
   character(*), parameter :: DEF_BREAKING_ROLLER_EFFECT = "NO"
   character(*), parameter :: DEF_BREAKING_SHOW_BREAKING = "YES"
   character(*), parameter :: DEF_BREAKING_VISBRK = "0.0"
   character(*), parameter :: DEF_BREAKING_WAVEMAKER_CBRK = "1.0"
   character(*), parameter :: DEF_BREAKING_WAVEMAKER_VIS = "NO"
   character(*), parameter :: DEF_BREAKING_WAVEMAKER_VISBRK = "0.0"
   ! ── foam ──
   character(*), parameter :: DEF_FOAM_BURSTTIMENONBREAKING = "1.0"
   character(*), parameter :: DEF_FOAM_CDFOAM = "0.5"
   character(*), parameter :: DEF_FOAM_FOAMTIMESCALE = "3.8"
   character(*), parameter :: DEF_FOAM_MINTHICK = "0.01"
   character(*), parameter :: DEF_FOAM_F_SOURCE = "0.05"
   ! ── friction ──
   character(*), parameter :: DEF_FRICTION_CD = "0.0"
   character(*), parameter :: DEF_FRICTION_FRICTION_MATRIX = "NO"
   character(*), parameter :: DEF_FRICTION_MANNING = "NO"
   ! ── geometry ──
   character(*), parameter :: DEF_GEOMETRY_BATHY_CORRECTION = "NO"
   character(*), parameter :: DEF_GEOMETRY_BATHY_TYPE = "flat"
   ! ── hot_start ──
   character(*), parameter :: DEF_HOT_START_BED_DEFORMATION = "NO"
   character(*), parameter :: DEF_HOT_START_OUTPUT_START_NUMBER = "0"
   character(*), parameter :: DEF_HOT_START_TIME = "0.0"
   ! ── meteo ──
   character(*), parameter :: DEF_METEO_AIRPRESSURE = "NO"
   character(*), parameter :: DEF_METEO_CDW = "0.002"
   character(*), parameter :: DEF_METEO_METEOGAUSIAN = "NO"
   character(*), parameter :: DEF_METEO_OUT_METEO = "YES"
   character(*), parameter :: DEF_METEO_SLIDEMODEL = "NO"
   character(*), parameter :: DEF_METEO_WINDCONSTANTFIELD = "NO"
   character(*), parameter :: DEF_METEO_WINDCRESTPERCENT = "999999.0"
   character(*), parameter :: DEF_METEO_WINDFORCE = "NO"
   character(*), parameter :: DEF_METEO_WINDHOLLANDMODEL = "NO"
   character(*), parameter :: DEF_METEO_WINDWAVEINTERACTION = "NO"
   ! ── numerics ──
   character(*), parameter :: DEF_NUMERICS_CFL = "0.5"
   character(*), parameter :: DEF_NUMERICS_FLUX_SOLVER = "hllc"
   character(*), parameter :: DEF_NUMERICS_FROUDE_CAP = "3.0"
   character(*), parameter :: DEF_NUMERICS_MIN_DEPTH = "0.1"
   character(*), parameter :: DEF_NUMERICS_RECONSTRUCTION = "fourth"
   ! ── obstacle ──
   character(*), parameter :: DEF_OBSTACLE_BREAKWATERABSORBCOEF = "10.0"
   character(*), parameter :: DEF_OBSTACLE_BREAKWATER_ABSORB_COEF = "0.0"
   ! ── output ──
   character(*), parameter :: DEF_OUTPUT_ARRIVAL_TIME_MIN_HEIGHT = "0.001"
   character(*), parameter :: DEF_OUTPUT_DEPTH_OUT = "NO"
   character(*), parameter :: DEF_OUTPUT_ETA_BLOW_VAL = "1.0e8"
   character(*), parameter :: DEF_OUTPUT_FIELD_IO_TYPE = "ASCII"
   character(*), parameter :: DEF_OUTPUT_NUMBER_STATIONS = "0"
   character(*), parameter :: DEF_OUTPUT_OUTPUT_RES = "1"
   character(*), parameter :: DEF_OUTPUT_RESULT_FOLDER = "./output/"
   character(*), parameter :: DEF_OUTPUT_STEADY_TIME = "999999.0"
   character(*), parameter :: DEF_OUTPUT_T_INTV_MEAN = "999999.0"
   ! ── physics ──
   character(*), parameter :: DEF_PHYSICS_BETA_REF = "-0.531"
   character(*), parameter :: DEF_PHYSICS_BREAKING = "NO"
   character(*), parameter :: DEF_PHYSICS_C_SMG = "0.0"
   character(*), parameter :: DEF_PHYSICS_DISP_TIME_LEFT = "NO"
   character(*), parameter :: DEF_PHYSICS_DISPERSION = "YES"
   character(*), parameter :: DEF_PHYSICS_GAMMA1 = "1.0"
   character(*), parameter :: DEF_PHYSICS_GAMMA2 = "1.0"
   character(*), parameter :: DEF_PHYSICS_GAMMA3 = "1.0"
   character(*), parameter :: DEF_PHYSICS_PERIODIC = "NO"
   character(*), parameter :: DEF_PHYSICS_SEDIMENT = "NO"
   character(*), parameter :: DEF_PHYSICS_SWE_ETA_DEP = "0.7"
   character(*), parameter :: DEF_PHYSICS_VISCOSITY_BREAKING = "YES"
   character(*), parameter :: DEF_PHYSICS_WATER_LEVEL = "0.0"
   character(*), parameter :: DEF_PHYSICS_WAVEMAKER = "NO"
   ! ── precipitation ──
   character(*), parameter :: DEF_PRECIPITATION_OUT_PRECIPITATION = "YES"
   character(*), parameter :: DEF_PRECIPITATION_RAINWAVEINTERACTION = "NO"
   ! ── sediment ──
   character(*), parameter :: DEF_SEDIMENT_AVALANCHE = "NO"
   character(*), parameter :: DEF_SEDIMENT_BEDLOAD = "NO"
   character(*), parameter :: DEF_SEDIMENT_BED_CHANGE = "NO"
   character(*), parameter :: DEF_SEDIMENT_COHESIVESEDIMENT = "NO"
   character(*), parameter :: DEF_SEDIMENT_E_COH = "0.0001"
   character(*), parameter :: DEF_SEDIMENT_HARD_BOTTOM = "NO"
   character(*), parameter :: DEF_SEDIMENT_MINDEPTHPICKUP = "0.1"
   character(*), parameter :: DEF_SEDIMENT_MORPH_FACTOR = "1"
   character(*), parameter :: DEF_SEDIMENT_PICKUPREDUCTION = "YES"
   character(*), parameter :: DEF_SEDIMENT_REDUCTIONPARAMETER = "0.65"
   character(*), parameter :: DEF_SEDIMENT_SDENSITY = "2.68"
   character(*), parameter :: DEF_SEDIMENT_SED_SCHEME = "Upwinding"
   character(*), parameter :: DEF_SEDIMENT_SEDIMENTMASSSOURCE = "NO"
   character(*), parameter :: DEF_SEDIMENT_SEDIMENTMOMENTDC = "NO"
   character(*), parameter :: DEF_SEDIMENT_SEDIMENTMOMENTEXG = "NO"
   character(*), parameter :: DEF_SEDIMENT_SHIELDS_CR = "0.055"
   character(*), parameter :: DEF_SEDIMENT_SOFTBED = "YES"
   character(*), parameter :: DEF_SEDIMENT_TAN_PHI = "0.7"
   character(*), parameter :: DEF_SEDIMENT_TAU_CR_COH = "0.001"
   character(*), parameter :: DEF_SEDIMENT_TAU_CRD_COH = "0.001"
   character(*), parameter :: DEF_SEDIMENT_A_COH = "0.1"
   character(*), parameter :: DEF_SEDIMENT_ALPHA_COH = "1.0"
   character(*), parameter :: DEF_SEDIMENT_B_COH = "2.0"
   character(*), parameter :: DEF_SEDIMENT_K_COH = "1e-06"
   character(*), parameter :: DEF_SEDIMENT_M_COH = "1.5"
   character(*), parameter :: DEF_SEDIMENT_N_COH = "0.5"
   character(*), parameter :: DEF_SEDIMENT_N_POROSITY = "0.47"
   ! ── simulation ──
   character(*), parameter :: DEF_SIMULATION_PLOT_INTV_STATION = "1.0"
   character(*), parameter :: DEF_SIMULATION_SCREEN_INTERVAL = "1.0"
   character(*), parameter :: DEF_SIMULATION_STATION_OUTPUT_BUFFER = "1000"
   character(*), parameter :: DEF_SIMULATION_T_START = "0.0"
   character(*), parameter :: DEF_SIMULATION_TIME_STEPPING_FIXED_DT = "NO"
   ! ── sponge ──
   character(*), parameter :: DEF_SPONGE_CDSPONGE = "5.0"
   character(*), parameter :: DEF_SPONGE_A_SPONGE = "5.0"
   character(*), parameter :: DEF_SPONGE_CD_SPONGE = "0.0"
   character(*), parameter :: DEF_SPONGE_CSP = "0.1"
   character(*), parameter :: DEF_SPONGE_DIFFUSION_SPONGE = "NO"
   character(*), parameter :: DEF_SPONGE_DIRECT_SPONGE = "NO"
   character(*), parameter :: DEF_SPONGE_FRICTION_SPONGE = "NO"
   character(*), parameter :: DEF_SPONGE_R_SPONGE = "0.85"
   character(*), parameter :: DEF_SPONGE_SPONGE_EAST_WIDTH = "0.0"
   character(*), parameter :: DEF_SPONGE_SPONGE_NORTH_WIDTH = "0.0"
   character(*), parameter :: DEF_SPONGE_SPONGE_SOUTH_WIDTH = "0.0"
   character(*), parameter :: DEF_SPONGE_SPONGE_WEST_WIDTH = "0.0"
   ! ── subgrid ──
   character(*), parameter :: DEF_SUBGRID_POROSITY = "NO"
   character(*), parameter :: DEF_SUBGRID_SUBMAINGRIDRATIO = "1"
   ! ── tide ──
   character(*), parameter :: DEF_TIDE_TIDAL_BC_ABS = "NO"
   character(*), parameter :: DEF_TIDE_TIDAL_BC_GEN_ABS = "NO"
   character(*), parameter :: DEF_TIDE_TIDEBCTYPE = "CONSTANT"
   character(*), parameter :: DEF_TIDE_WAVEMAKERPOINTNUM = "30"
   ! ── vessel ──
   character(*), parameter :: DEF_VESSEL_CLEARANCE = "1.0"
   character(*), parameter :: DEF_VESSEL_CDDEEPDRAFT = "0.1"
   character(*), parameter :: DEF_VESSEL_DEEP_DRAFT = "NO"
   character(*), parameter :: DEF_VESSEL_FRICTIONMETHOD = "YES"
   character(*), parameter :: DEF_VESSEL_MASKMETHOD = "YES"
   character(*), parameter :: DEF_VESSEL_NUMVESSEL = "1"
   character(*), parameter :: DEF_VESSEL_OUT_VESSEL = "YES"
   character(*), parameter :: DEF_VESSEL_PROPELLER = "NO"
   character(*), parameter :: DEF_VESSEL_VISDEEPDRAFT = "0.1"
   character(*), parameter :: DEF_VESSEL_VISCOSITYMETHOD = "NO"
   ! ── wavemaker ──
   character(*), parameter :: DEF_WAVEMAKER_AMP = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_AMP_WK = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_A_SPONGE_WAVEMAKER = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_DEP = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_DEP_WK = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_DELTA_WK = "0.5"
   character(*), parameter :: DEF_WAVEMAKER_ETA_LIMITER = "NO"
   character(*), parameter :: DEF_WAVEMAKER_EQUALENERGY = "NO"
   character(*), parameter :: DEF_WAVEMAKER_FREQMAX = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_FREQMIN = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_FREQPEAK = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_GAMMATMA = "3.3"
   character(*), parameter :: DEF_WAVEMAKER_HMO = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_LAGTIME = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_NFREQ = "45"
   character(*), parameter :: DEF_WAVEMAKER_NTHETA = "1"
   character(*), parameter :: DEF_WAVEMAKER_NUMWAVECOMP = "1"
   character(*), parameter :: DEF_WAVEMAKER_PEAKPERIOD = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_R_SPONGE_WAVEMAKER = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SIGMA_THETA = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SOLITARYPOSITIVEDIRECTION = "YES"
   character(*), parameter :: DEF_WAVEMAKER_THETAPEAK = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_THETA_WK = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_TIME_RAMP = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_TPERIOD = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_WAVE_DATA_TYPE = "DATA_1D"
   character(*), parameter :: DEF_WAVEMAKER_WID = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_WIDTHWAVEMAKER = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_XWAVEMAKER = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_XC = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_XC_WK = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_YC = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_YC_WK = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_YWIDTH_WK = "999999.0"
   character(*), parameter :: DEF_WAVEMAKER_A0_NWAVE = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_ALPHA_C = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_DEP_NWAVE = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_GAMMA_NWAVE = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_TYPE = "nothing"
   character(*), parameter :: DEF_WAVEMAKER_X1_NWAVE = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_X2_NWAVE = "0.0"

end module model_config_defaults_mod
