# Only require PFUNIT for unit testing
if(ENABLE_TESTING)
    file(GLOB PFUNIT_DIRS "${CMAKE_CURRENT_SOURCE_DIR}/extern/pfunit/installed/PFUNIT-*")
    
    list(LENGTH PFUNIT_DIRS PFUNIT_COUNT)
    if(PFUNIT_COUNT EQUAL 0)
        message(FATAL_ERROR "No pFUnit installation found in 'extern/pfunit/installed/'. Run 'install_deps.sh' first.")
    elseif(PFUNIT_COUNT GREATER 1)
        list(SORT PFUNIT_DIRS)
        list(REVERSE PFUNIT_DIRS)
        list(GET PFUNIT_DIRS 0 LATEST_PFUNIT)
        message(WARNING "Multiple pFUnit versions found. Using latest: ${LATEST_PFUNIT}")
        set(PFUNIT_DIR "${LATEST_PFUNIT}/cmake")
    else()
        list(GET PFUNIT_DIRS 0 PFUNIT_DIR)
        set(PFUNIT_DIR "${PFUNIT_DIR}/cmake")
    endif()
    
    find_package(PFUNIT REQUIRED PATHS "${PFUNIT_DIR}" NO_DEFAULT_PATH)
endif()
