
[project]
name = "FUNWAVE-TVD"
version = "4.0-beta"
requires-python = ">=3.10"
dependencies = [
    "typer",
    "rich",
    "pre-commit>=4.6.0",
    "numpy>=2.2.6",
    "weasyprint>=68.1",
    "plotly>=6.7.0",
    "kaleido>=1.3.0",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.6",
    "mkdocs-bibtex>=4.4.0",
    "pymdown-extensions>=10.21.3",
    "mkdocs-swan>=0.4.0",
    "matplotlib>=3.10.9",
]

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "build_*",
    "test/regression/worktrees/*"
]

# Same as Black.
line-length = 132

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings by default.
select = [
    "E4", "E7", "E9", "F", # Pyflakes, Pycodestyle E4, E7, E9
    "I",                   # isort
    "N",                   # pep8-naming
    "D",                   # pydocstyle
    "UP",                  # pyupgrade
]
ignore = [
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[dependency-groups]
dev = [
    "cmake-format>=0.6.13",
    "fprettify>=0.3.7",
]

[tool.ruff.lint.isort]
known-first-party = ["test"]

[tool.fprettify]
indent = 2
whitespace = 2
max-line-length = 132
recursive = true

[tool.cmake-format]
line_width = 132
tab_size = 2

[tool.shfmt]
indent = 2

