! allow(E001)
! =================================================================
!  GENERATED FILE — DO NOT EDIT.
!  Source:    src/model/registry.yaml
!  Generator: scripts/gen_registry.py   (rerun after registry edits)
!  Sync test: scripts/gen_registry.py --check
! =================================================================
!> @file config_defaults.f90
!> @brief Generated YAML-parameter default constants (registry single source).
module model_config_defaults_mod
   implicit none
   public

   ! ── boundaries ──
   character(*), parameter :: DEF_BOUNDARIES_EAST_SPONGE_DIFFUSION_NU = "0.1"
   character(*), parameter :: DEF_BOUNDARIES_EAST_SPONGE_DIRECT_A = "5.0"
   character(*), parameter :: DEF_BOUNDARIES_EAST_SPONGE_DIRECT_R = "0.85"
   character(*), parameter :: DEF_BOUNDARIES_EAST_SPONGE_FRICTION_CD = "0.0"
   character(*), parameter :: DEF_BOUNDARIES_EAST_SPONGE_WIDTH = "0.0"
   character(*), parameter :: DEF_BOUNDARIES_NORTH_SPONGE_DIFFUSION_NU = "0.1"
   character(*), parameter :: DEF_BOUNDARIES_NORTH_SPONGE_DIRECT_A = "5.0"
   character(*), parameter :: DEF_BOUNDARIES_NORTH_SPONGE_DIRECT_R = "0.85"
   character(*), parameter :: DEF_BOUNDARIES_NORTH_SPONGE_FRICTION_CD = "0.0"
   character(*), parameter :: DEF_BOUNDARIES_NORTH_SPONGE_WIDTH = "0.0"
   character(*), parameter :: DEF_BOUNDARIES_RELAXATION_CELLS = "30"
   character(*), parameter :: DEF_BOUNDARIES_SOUTH_SPONGE_DIFFUSION_NU = "0.1"
   character(*), parameter :: DEF_BOUNDARIES_SOUTH_SPONGE_DIRECT_A = "5.0"
   character(*), parameter :: DEF_BOUNDARIES_SOUTH_SPONGE_DIRECT_R = "0.85"
   character(*), parameter :: DEF_BOUNDARIES_SOUTH_SPONGE_FRICTION_CD = "0.0"
   character(*), parameter :: DEF_BOUNDARIES_SOUTH_SPONGE_WIDTH = "0.0"
   character(*), parameter :: DEF_BOUNDARIES_WEST_SPONGE_DIFFUSION_NU = "0.1"
   character(*), parameter :: DEF_BOUNDARIES_WEST_SPONGE_DIRECT_A = "5.0"
   character(*), parameter :: DEF_BOUNDARIES_WEST_SPONGE_DIRECT_R = "0.85"
   character(*), parameter :: DEF_BOUNDARIES_WEST_SPONGE_FRICTION_CD = "0.0"
   character(*), parameter :: DEF_BOUNDARIES_WEST_SPONGE_WIDTH = "0.0"
   ! ── breaking ──
   character(*), parameter :: DEF_BREAKING_CBRK1 = "0.65"
   character(*), parameter :: DEF_BREAKING_CBRK2 = "0.35"
   character(*), parameter :: DEF_BREAKING_MODEL = "eddy_viscosity"
   character(*), parameter :: DEF_BREAKING_NU_BKG = "0.0"
   character(*), parameter :: DEF_BREAKING_ROLLER = "NO"
   character(*), parameter :: DEF_BREAKING_ROLLER_EFFECT = "NO"
   character(*), parameter :: DEF_BREAKING_SHOW_BREAKING = "YES"
   character(*), parameter :: DEF_BREAKING_VISBRK = "0.0"
   character(*), parameter :: DEF_BREAKING_WAVEMAKER_CBRK = "1.0"
   character(*), parameter :: DEF_BREAKING_WAVEMAKER_VIS = "NO"
   character(*), parameter :: DEF_BREAKING_WAVEMAKER_VISBRK = "0.0"
   ! ── foam ──
   character(*), parameter :: DEF_FOAM_BURST_TIME_NON_BREAKING = "1.0"
   character(*), parameter :: DEF_FOAM_CD = "0.5"
   character(*), parameter :: DEF_FOAM_MIN_THICKNESS = "0.01"
   character(*), parameter :: DEF_FOAM_SOURCE_COEF = "0.05"
   character(*), parameter :: DEF_FOAM_TIME_SCALE = "3.8"
   ! ── grid ──
   character(*), parameter :: DEF_GRID_BATHY_CORRECTION = "NO"
   character(*), parameter :: DEF_GRID_BATHY_TYPE = "flat"
   character(*), parameter :: DEF_GRID_CRS_ORIGIN_X = "0.0"
   character(*), parameter :: DEF_GRID_CRS_ORIGIN_Y = "0.0"
   character(*), parameter :: DEF_GRID_CRS_ROTATION = "0.0"
   ! ── hot_start ──
   character(*), parameter :: DEF_HOT_START_BED_DEFORMATION = "NO"
   character(*), parameter :: DEF_HOT_START_OUTPUT_START_NUMBER = "0"
   character(*), parameter :: DEF_HOT_START_TIME = "0.0"
   ! ── initial ──
   character(*), parameter :: DEF_INITIAL_SINE_MODE_AMPLITUDE = "0.0"
   character(*), parameter :: DEF_INITIAL_SINE_MODE_DEPTH = "0.0"
   character(*), parameter :: DEF_INITIAL_SINE_MODE_MODE_X = "1"
   character(*), parameter :: DEF_INITIAL_SINE_MODE_MODE_Y = "0"
   character(*), parameter :: DEF_INITIAL_SOLITARY_AMPLITUDE = "0.0"
   character(*), parameter :: DEF_INITIAL_SOLITARY_DEPTH = "0.0"
   character(*), parameter :: DEF_INITIAL_SOLITARY_DIRECTION = "+x"
   character(*), parameter :: DEF_INITIAL_SOLITARY_X_CENTER = "0.0"
   character(*), parameter :: DEF_INITIAL_SOLITARY_Y_CENTER = "0.0"
   character(*), parameter :: DEF_INITIAL_WATER_LEVEL = "0.0"
   ! ── meteo ──
   character(*), parameter :: DEF_METEO_HOLLAND_AIR_PRESSURE = "NO"
   character(*), parameter :: DEF_METEO_HOLLAND_CD = "0.002"
   character(*), parameter :: DEF_METEO_HOLLAND_WAVE_INTERACTION = "NO"
   character(*), parameter :: DEF_METEO_HOLLAND_WIND_FORCE = "NO"
   character(*), parameter :: DEF_METEO_WIND_CD = "0.002"
   character(*), parameter :: DEF_METEO_WIND_WAVE_INTERACTION = "NO"
   ! ── numerics ──
   character(*), parameter :: DEF_NUMERICS_CFL = "0.5"
   character(*), parameter :: DEF_NUMERICS_FLUX_SOLVER = "hllc"
   character(*), parameter :: DEF_NUMERICS_FROUDE_CAP = "3.0"
   character(*), parameter :: DEF_NUMERICS_MIN_DEPTH = "0.1"
   character(*), parameter :: DEF_NUMERICS_RECONSTRUCTION = "fourth"
   character(*), parameter :: DEF_NUMERICS_TRIDIAG_CHUNK = "48"
   character(*), parameter :: DEF_NUMERICS_TRIDIAG_TRANSPOSE_MIN_PY = "40"
   ! ── obstacle ──
   character(*), parameter :: DEF_OBSTACLE_BREAKWATER_ABSORB_COEF = "10.0"
   ! ── output ──
   character(*), parameter :: DEF_OUTPUT_ARRIVAL_TIME_MIN_HEIGHT = "0.001"
   character(*), parameter :: DEF_OUTPUT_DEPTH_OUT = "NO"
   character(*), parameter :: DEF_OUTPUT_FIELD_IO_TYPE = "ASCII"
   character(*), parameter :: DEF_OUTPUT_LAYOUT = "chunked"
   character(*), parameter :: DEF_OUTPUT_MAX_FILE_SIZE = "50.0"
   character(*), parameter :: DEF_OUTPUT_MEANS_STEADY_TIME = "0.0"
   character(*), parameter :: DEF_OUTPUT_RESULT_FOLDER = "./output/"
   ! ── physics ──
   character(*), parameter :: DEF_PHYSICS_DISPERSION_BETA_REF = "-0.531"
   character(*), parameter :: DEF_PHYSICS_DISPERSION_SCHEME = "fully_nonlinear"
   character(*), parameter :: DEF_PHYSICS_DISPERSION_SWE_ETA_DEP = "0.8"
   character(*), parameter :: DEF_PHYSICS_DISPERSION_SWE_ETA_RAMP = "0.1"
   ! ── sediment ──
   character(*), parameter :: DEF_SEDIMENT_BED_CHANGE = "NO"
   character(*), parameter :: DEF_SEDIMENT_BEDLOAD = "NO"
   character(*), parameter :: DEF_SEDIMENT_COHESIVE_A = "0.1"
   character(*), parameter :: DEF_SEDIMENT_COHESIVE_ALPHA = "1.0"
   character(*), parameter :: DEF_SEDIMENT_COHESIVE_B = "2.0"
   character(*), parameter :: DEF_SEDIMENT_COHESIVE_E = "0.0001"
   character(*), parameter :: DEF_SEDIMENT_COHESIVE_M = "1.5"
   character(*), parameter :: DEF_SEDIMENT_COHESIVE_N = "0.5"
   character(*), parameter :: DEF_SEDIMENT_COHESIVE_SOFT_BED = "YES"
   character(*), parameter :: DEF_SEDIMENT_COHESIVE_TAU_CRD = "0.001"
   character(*), parameter :: DEF_SEDIMENT_FEEDBACK_MASS_SOURCE = "NO"
   character(*), parameter :: DEF_SEDIMENT_FEEDBACK_MOMENT_DC = "NO"
   character(*), parameter :: DEF_SEDIMENT_FEEDBACK_MOMENT_EXG = "NO"
   character(*), parameter :: DEF_SEDIMENT_MIN_DEPTH_PICKUP = "0.1"
   character(*), parameter :: DEF_SEDIMENT_MORPH_FACTOR = "1"
   character(*), parameter :: DEF_SEDIMENT_PICKUP_REDUCTION = "YES"
   character(*), parameter :: DEF_SEDIMENT_POROSITY = "0.47"
   character(*), parameter :: DEF_SEDIMENT_REDUCTION_PARAMETER = "0.65"
   character(*), parameter :: DEF_SEDIMENT_SCHEME = "upwinding"
   character(*), parameter :: DEF_SEDIMENT_SHIELDS_CR = "0.055"
   character(*), parameter :: DEF_SEDIMENT_SPECIFIC_GRAVITY = "2.68"
   ! ── simulation ──
   character(*), parameter :: DEF_SIMULATION_SCREEN_INTERVAL = "1.0"
   character(*), parameter :: DEF_SIMULATION_T_START = "0.0"
   character(*), parameter :: DEF_SIMULATION_TIME_STEPPING_FIXED_DT = "NO"
   ! ── subgrid ──
   character(*), parameter :: DEF_SUBGRID_RATIO = "1"
   character(*), parameter :: DEF_SUBGRID_WRITE_POROSITY = "NO"
   ! ── vessel ──
   character(*), parameter :: DEF_VESSEL_COUNT = "1"
   character(*), parameter :: DEF_VESSEL_DEEP_DRAFT_MASK = "YES"
   character(*), parameter :: DEF_VESSEL_PROPELLER = "NO"
   ! ── wavemaker ──
   character(*), parameter :: DEF_WAVEMAKER_SOURCE_DELTA = "0.5"
   character(*), parameter :: DEF_WAVEMAKER_SOURCE_DEPTH = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SOURCE_TIME_RAMP = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SOURCE_X_CENTER = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SOURCE_Y_CENTER = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SOURCE_Y_WIDTH = "999999.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_AMPLITUDE = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_DIRECTION = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_DIRECTIONAL_PEAK = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_DISCRETIZATION_COHERENCE_PERCENT = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_DISCRETIZATION_EQUAL_ENERGY = "NO"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_DISCRETIZATION_FREQ_BINS = "45"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_DISCRETIZATION_METHOD = "grid"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_DISCRETIZATION_THETA_BINS = "24"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_FORMAT = "DATA_1D"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_FREQ_MAX = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_FREQ_MIN = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_FREQ_PEAK = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_GAMMA = "3.3"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_HM0 = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_N = "1"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_NORMALIZE = "band"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_PERIOD = "0.0"
   character(*), parameter :: DEF_WAVEMAKER_SPECTRUM_PERIOD_PEAK = "0.0"

end module model_config_defaults_mod
