function(print_summary)
  string(TOUPPER ${project_name} _prj_uc)
  message(STATUS "")
  message(STATUS "========== ${_prj_uc} Configuration Summary ==========")
  message(STATUS "  Fortran compiler  : ${CMAKE_Fortran_COMPILER_ID}")
  message(STATUS "  ENABLE_TESTING    : ${ENABLE_TESTING}")
  # message(STATUS "  ENABLE_TESTING    : ${ENABLE_TESTING}")
  message(STATUS "===================================================")
endfunction()
