function(print_summary)
  string(TOUPPER ${project_name} _prj_uc)
  message(STATUS "")
  message(STATUS "========== ${_prj_uc} Configuration Summary ==========")
  message(STATUS "  Fortran compiler  : ${CMAKE_Fortran_COMPILER_ID}")
  message(STATUS "  USE_FOAM          : ${USE_FOAM}")
  message(STATUS "  USE_METEO         : ${USE_METEO}")
  message(STATUS "  USE_PERCIPITATION : ${USE_PERCIPITATION}")
  message(STATUS "  USE_SEDIMENT      : ${USE_SPHERICAL}")
  message(STATUS "  USE_SUBGRID       : ${USE_SUBGRID}")
  message(STATUS "  USE_TRACKING      : ${USE_TRACKING}")
  message(STATUS "  USE_VESSEL        : ${USE_VESSEL}")
  message(STATUS "  USE_MPI           : ${USE_MPI}")
  message(STATUS "  USE_SPHERICAL     : ${USE_SPHERICAL}")
  message(STATUS "  USE_DOUBLE        : ${USE_DOUBLE}")
  message(STATUS "  module_flags      : ${module_flags}")
  message(STATUS "===================================================")
endfunction()
