# CMake generated Testfile for 
# Source directory: /Users/rdchlmyl/repos/mayhlFUNWAVE/test/core
# Build directory: /Users/rdchlmyl/repos/mayhlFUNWAVE/build_dev/test/core
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_path_mod]=] "/Users/rdchlmyl/repos/mayhlFUNWAVE/build_dev/test/core/test_path_mod" "--verbose")
set_tests_properties([=[test_path_mod]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "Encountered 1 or more failures/errors during testing" WORKING_DIRECTORY "/Users/rdchlmyl/repos/mayhlFUNWAVE/build_dev/test/core" _BACKTRACE_TRIPLES "/Users/rdchlmyl/repos/mayhlFUNWAVE/extern/pfunit/installed/PFUNIT-4.18/include/add_pfunit_ctest.cmake;197;add_test;/Users/rdchlmyl/repos/mayhlFUNWAVE/cmake/modules/utils.cmake;71;add_pfunit_ctest;/Users/rdchlmyl/repos/mayhlFUNWAVE/test/core/CMakeLists.txt;3;qadd_pfunit_ctest;/Users/rdchlmyl/repos/mayhlFUNWAVE/test/core/CMakeLists.txt;0;")
add_test([=[test_range_parser]=] "/Users/rdchlmyl/repos/mayhlFUNWAVE/build_dev/test/core/test_range_parser" "--verbose")
set_tests_properties([=[test_range_parser]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "Encountered 1 or more failures/errors during testing" WORKING_DIRECTORY "/Users/rdchlmyl/repos/mayhlFUNWAVE/build_dev/test/core" _BACKTRACE_TRIPLES "/Users/rdchlmyl/repos/mayhlFUNWAVE/extern/pfunit/installed/PFUNIT-4.18/include/add_pfunit_ctest.cmake;197;add_test;/Users/rdchlmyl/repos/mayhlFUNWAVE/cmake/modules/utils.cmake;71;add_pfunit_ctest;/Users/rdchlmyl/repos/mayhlFUNWAVE/test/core/CMakeLists.txt;4;qadd_pfunit_ctest;/Users/rdchlmyl/repos/mayhlFUNWAVE/test/core/CMakeLists.txt;0;")
add_test([=[test_logging]=] "/Users/rdchlmyl/repos/mayhlFUNWAVE/build_dev/test/core/test_logging" "--verbose")
set_tests_properties([=[test_logging]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "Encountered 1 or more failures/errors during testing" WORKING_DIRECTORY "/Users/rdchlmyl/repos/mayhlFUNWAVE/build_dev/test/core" _BACKTRACE_TRIPLES "/Users/rdchlmyl/repos/mayhlFUNWAVE/extern/pfunit/installed/PFUNIT-4.18/include/add_pfunit_ctest.cmake;197;add_test;/Users/rdchlmyl/repos/mayhlFUNWAVE/cmake/modules/utils.cmake;71;add_pfunit_ctest;/Users/rdchlmyl/repos/mayhlFUNWAVE/test/core/CMakeLists.txt;5;qadd_pfunit_ctest;/Users/rdchlmyl/repos/mayhlFUNWAVE/test/core/CMakeLists.txt;0;")
add_test([=[test_yaml_input_serial]=] "/Users/rdchlmyl/repos/mayhlFUNWAVE/build_dev/test/core/test_yaml_input_serial" "--verbose")
set_tests_properties([=[test_yaml_input_serial]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "Encountered 1 or more failures/errors during testing" WORKING_DIRECTORY "/Users/rdchlmyl/repos/mayhlFUNWAVE/build_dev/test/core" _BACKTRACE_TRIPLES "/Users/rdchlmyl/repos/mayhlFUNWAVE/extern/pfunit/installed/PFUNIT-4.18/include/add_pfunit_ctest.cmake;197;add_test;/Users/rdchlmyl/repos/mayhlFUNWAVE/cmake/modules/utils.cmake;71;add_pfunit_ctest;/Users/rdchlmyl/repos/mayhlFUNWAVE/test/core/CMakeLists.txt;6;qadd_pfunit_ctest;/Users/rdchlmyl/repos/mayhlFUNWAVE/test/core/CMakeLists.txt;0;")
add_test([=[test_yaml_input_parallel]=] "/usr/local/bin/mpiexec" "-n" "2" "/Users/rdchlmyl/repos/mayhlFUNWAVE/build_dev/test/core/test_yaml_input_parallel" "--verbose")
set_tests_properties([=[test_yaml_input_parallel]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "Encountered 1 or more failures/errors during testing" WORKING_DIRECTORY "/Users/rdchlmyl/repos/mayhlFUNWAVE/build_dev/test/core" _BACKTRACE_TRIPLES "/Users/rdchlmyl/repos/mayhlFUNWAVE/extern/pfunit/installed/PFUNIT-4.18/include/add_pfunit_ctest.cmake;191;add_test;/Users/rdchlmyl/repos/mayhlFUNWAVE/cmake/modules/utils.cmake;71;add_pfunit_ctest;/Users/rdchlmyl/repos/mayhlFUNWAVE/test/core/CMakeLists.txt;7;qadd_pfunit_ctest;/Users/rdchlmyl/repos/mayhlFUNWAVE/test/core/CMakeLists.txt;0;")
